In [1]:
import zarr
import napari
import copick
import copick_utils

config_str = """{
    "config_type": "cryoet_data_portal",
    "name": "polnet",
    "description": "A Data Portal project.",
    "version": "1.0.0",

    "pickable_objects": [
        {
            "name": "membrane",
            "is_particle": false,
            "label": 1,
            "go_id": "GO:0016020",            
            "color": [150,150, 150, 255],
            "radius": 10
        },
        {
            "name": "adp-mitochondrial",
            "is_particle": true,
            "pdb_id": "6MRD",
            "go_id": "GO:1990220",
            "label": 2,
            "color": [  0, 117, 220, 255],
            "radius": 75,
            "map_threshold": 0.037
        },
        {
            "name": "alkaline-phosphate",
            "is_particle": true,
            "pdb_id": "1ZEF",
            "go_id": "UniProtKB:P05187",
            "label": 3,
            "color": [  0, 117, 220, 255],
            "radius": 75,
            "map_threshold": 0.037
        },
        {
            "name": "nucleosome",
            "is_particle": true,
            "pdb_id": "6UPH",
            "go_id": "GO:0000786",
            "label": 4,
            "color": [  0, 117, 220, 255],
            "radius": 65,
            "map_threshold": 0.037
        },        
        {
            "name": "ribosome",
            "is_particle": true,
            "pdb_id": "7TM3",
            "go_id": "GO:0022626",
            "label": 5,
            "color": [  0, 117, 220, 255],
            "radius": 165,
            "map_threshold": 0.037
        },
        {
            "name": "vault",
            "is_particle": true,
            "pdb_id": "7PKZ",
            "go_id": "UniProtKB:Q62667",
            "label": 6,
            "color": [  0, 117, 220, 255],
            "radius": 165,
            "map_threshold": 0.037
        },
        {
            "name": "virus-like-capsid",
            "is_particle": true,
            "pdb_id": "6NK5",
            "go_id": "GO:0170047",
            "label": 7,
            "color": [  0, 117, 220, 255],
            "radius": 140,
            "map_threshold": 0.037
        }             
    ],

    "overlay_root": "./data",

    "overlay_fs_args": {
        "auto_mkdir": true
    },

    "dataset_ids": [10439]
}
"""

# Use copick
config_file = "./my_synthetic_data_10439_dataportal.json"

with open(config_file, "w") as f:
    f.write(config_str)

root = copick.from_file(config_file)

run_name = "16193"
example_run = root.get_run(run_name)
voxel_spacing= 10
tomo_type = "wbp"
tomogram = example_run.voxel_spacings[0].tomograms[0]

# Open zarr
z = zarr.open(tomogram.zarr())
img = z["0"]# Get our highest resolution scale

crop = img[100:110, 200:400, 200:400]

# Open viewer and add image
viewer = napari.Viewer()
viewer.add_image(crop)

/Users/kharrington/.album/micromamba/envs/nesoi/lib/python3.10/site-packages/morphometrics_engine/measure.py:4: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm


<Image layer 'crop' at 0x1c7e1d960>

In [2]:
import numpy as np
from skimage.segmentation import slic
from skimage import img_as_float

# Convert the image to a float array
img_float = img_as_float(crop)

segments = slic(img_float, n_segments=1000, compactness=10.0, start_label=1, channel_axis=None)

# Add the segmented image to the napari viewer
viewer.add_labels(segments)

# segments is the result containing integer labels for each superpixel
print(segments)


[[[  1   1   1 ...  29  29  29]
  [  1   1   1 ...  29  29  29]
  [  1   1   1 ...  29  29  29]
  ...
  [813 813 813 ... 841 841 841]
  [813 813 813 ... 841 841 841]
  [813 813 813 ... 841 841 841]]

 [[  1   1   1 ...  29  29  29]
  [  1   1   1 ...  29  29  29]
  [  1   1   1 ...  29  29  29]
  ...
  [813 813 813 ... 841 841 841]
  [813 813 813 ... 841 841 841]
  [813 813 813 ... 841 841 841]]

 [[  1   1   1 ...  29  29  29]
  [  1   1   1 ...  29  29  29]
  [  1   1   1 ...  29  29  29]
  ...
  [813 813 813 ... 841 841 841]
  [813 813 813 ... 841 841 841]
  [813 813 813 ... 841 841 841]]

 ...

 [[  1   1   1 ...  29  29  29]
  [  1   1   1 ...  29  29  29]
  [  1   1   1 ...  29  29  29]
  ...
  [813 813 813 ... 841 841 841]
  [813 813 813 ... 841 841 841]
  [813 813 813 ... 841 841 841]]

 [[  1   1   1 ...  29  29  29]
  [  1   1   1 ...  29  29  29]
  [  1   1   1 ...  29  29  29]
  ...
  [813 813 813 ... 841 841 841]
  [813 813 813 ... 841 841 841]
  [813 813 813 ... 841 841 8